import {styleTags, tags as t} from "@lezer/highlight"

export const rubyHighlighting = styleTags({
  "def class module end do begin rescue ensure raise return yield": t.keyword,
  "if elsif else unless case when then while until for in break next": t.keyword,
  "and or not": t.keyword,
  "nil true false self": t.atom,
  Identifier: t.variableName,
  "MethodDef/Identifier": t.function(t.definition(t.variableName)),
  "MethodCall/Identifier": t.function(t.variableName),
  InstanceVariable: t.special(t.variableName),
  ClassVariable: t.special(t.variableName),
  GlobalVariable: t.special(t.variableName),
  Constant: t.typeName,
  Symbol: t.atom,
  Integer: t.integer,
  Float: t.float,
  CharacterLiteral: t.character,
  SingleQuotedString: t.string,
  InterpolatedString: t.string,
  StringContent: t.string,
  StringEscape: t.escape,
  InterpolationStart: t.special(t.brace),
  InterpolationEnd: t.special(t.brace),
  LineComment: t.lineComment,
  BlockComment: t.blockComment,
  "( )": t.paren,
  "[ ]": t.squareBracket,
  "{ }": t.brace,
  ". &.": t.derefOperator,
  ", ;": t.separator,
  'ArithOp "-" "*" "**"': t.arithmeticOperator,
  CompareOp: t.compareOperator,
  "AssignOp": t.updateOperator,
  LogicOp: t.logicOperator,
})
