import {styleTags, tags as t} from "@lezer/highlight"

export const rubyHighlighting = styleTags({
  "def class module end do begin rescue ensure raise return yield": t.keyword,
  "if elsif else unless case when then while until for in break next": t.keyword,
  "and or not": t.keyword,
  "nil true false self": t.atom,
  "super __FILE__ __LINE__ __ENCODING__": t.atom,
  "require require_relative include extend prepend attr_reader attr_writer attr_accessor": t.keyword,
  "public private protected": t.modifier,
  "lambda proc": t.keyword,
  Identifier: t.variableName,
  "MethodDef/Identifier": t.function(t.definition(t.variableName)),
  "MethodCall/Identifier": t.function(t.variableName),
  InstanceVariable: t.special(t.variableName),
  ClassVariable: t.special(t.variableName),
  GlobalVariable: t.special(t.variableName),
  Constant: t.typeName,
  Symbol: t.atom,
  Integer: t.integer,
  Float: t.float,
  String: t.string,
  Regex: t.regexp,
  LineComment: t.lineComment,
  BlockComment: t.blockComment,
  "( )": t.paren,
  "[ ]": t.squareBracket,
  "{ }": t.brace,
  ".": t.derefOperator,
  ", ;": t.separator,
  'ArithOp "-"': t.arithmeticOperator,
  CompareOp: t.compareOperator,
  AssignOp: t.definitionOperator,
  LogicOp: t.logicOperator,
})
