export declare const Regex: number
export declare const divideOp: number
export declare const Heredoc: number
export declare const lessThanOp: number
export declare const lessThanEqOp: number
export declare const inheritsOp: number
export declare const shiftLeftOp: number
export declare const PercentStringLiteral: number
export declare const moduloOp: number
export declare const Symbol: number
export declare const colonOp: number
export declare const greaterThanOp: number
export declare const greaterThanEqOp: number
export declare const shiftRightOp: number
